-- 使用 12c+ 语法，主键为 IDENTITY（BY DEFAULT 允许显式插入）
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(11) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    nickname VARCHAR2(100),
    avatar VARCHAR2(255),
    signature VARCHAR2(500),
    gender VARCHAR2(20),
    location VARCHAR2(255),
    birth_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    last_login TIMESTAMP,
    active NUMBER(1) DEFAULT 1
  )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE messages (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id NUMBER(19) NOT NULL,
    receiver_id NUMBER(19) NOT NULL,
    content CLOB,
    type VARCHAR2(20) NOT NULL,
    file_path VARCHAR2(255),
    file_name VARCHAR2(100),
    file_size NUMBER(19),
    is_read NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE chat_groups (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR2(100) NOT NULL,
    group_avatar VARCHAR2(255),
    group_description CLOB,
    creator_id NUMBER(19) NOT NULL,
    member_count NUMBER(10) DEFAULT 0 NOT NULL,
    max_members NUMBER(10) DEFAULT 500 NOT NULL,
    is_public NUMBER(1) DEFAULT 1 NOT NULL,
    invite_code VARCHAR2(20) UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE group_members (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    group_nickname VARCHAR2(50),
    role VARCHAR2(20) NOT NULL,
    is_muted NUMBER(1) DEFAULT 0 NOT NULL,
    mute_end_time TIMESTAMP,
    joined_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uniq_group_user UNIQUE (group_id, user_id)
  )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE group_messages (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER(19) NOT NULL,
    sender_id NUMBER(19) NOT NULL,
    content CLOB,
    type VARCHAR2(20) NOT NULL,
    file_path VARCHAR2(255),
    file_name VARCHAR2(100),
    file_size NUMBER(19),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE friendships (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    friend_id NUMBER(19) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    accepted_at TIMESTAMP,
    CONSTRAINT uniq_user_friend UNIQUE (user_id, friend_id)
  )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 索引与外键
CREATE INDEX idx_messages_sender ON messages(sender_id);
CREATE INDEX idx_messages_receiver ON messages(receiver_id);

CREATE INDEX idx_groups_creator ON chat_groups(creator_id);

CREATE INDEX idx_group_members_group ON group_members(group_id);
CREATE INDEX idx_group_members_user ON group_members(user_id);

CREATE INDEX idx_group_messages_group ON group_messages(group_id);
CREATE INDEX idx_group_messages_sender ON group_messages(sender_id);

CREATE INDEX idx_friendships_user ON friendships(user_id);
CREATE INDEX idx_friendships_friend ON friendships(friend_id);

ALTER TABLE messages ADD CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id);
ALTER TABLE messages ADD CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(id);
ALTER TABLE chat_groups ADD CONSTRAINT fk_groups_creator FOREIGN KEY (creator_id) REFERENCES users(id);
ALTER TABLE group_members ADD CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES chat_groups(id);
ALTER TABLE group_members ADD CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE group_messages ADD CONSTRAINT fk_group_messages_group FOREIGN KEY (group_id) REFERENCES chat_groups(id);
ALTER TABLE group_messages ADD CONSTRAINT fk_group_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id);
ALTER TABLE friendships ADD CONSTRAINT fk_friendships_user FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE friendships ADD CONSTRAINT fk_friendships_friend FOREIGN KEY (friend_id) REFERENCES users(id);

